export enum State {
  National = "National",
  Alabama = "Alabama",
  Alaska = "Alaska",
  Arizona = "Arizona",
  Arkansas = "Arkansas",
  California = "California",
  Colorado = "Colorado",
  Connecticut = "Connecticut",
  Delaware = "Delaware",
  Florida = "Florida",
  Georgia = "Georgia",
  Hawaii = "Hawaii",
  Idaho = "Idaho",
  Illinois = "Illinois",
  Indiana = "Indiana",
  Iowa = "Iowa",
  Kansas = "Kansas",
  Kentucky = "Kentucky",
  Louisiana = "Louisiana",
  Maine = "Maine",
  Maryland = "Maryland",
  Massachusetts = "Massachusetts",
  Michigan = "Michigan",
  Minnesota = "Minnesota",
  Mississippi = "Mississippi",
  Missouri = "Missouri",
  Montana = "Montana",
  Nebraska = "Nebraska",
  Nevada = "Nevada",
  NewHampshire = "New Hampshire",
  NewJersey = "New Jersey",
  NewMexico = "New Mexico",
  NewYork = "New York",
  NorthCarolina = "North Carolina",
  NorthDakota = "North Dakota",
  Ohio = "Ohio",
  Oklahoma = "Oklahoma",
  Oregon = "Oregon",
  Pennsylvania = "Pennsylvania",
  RhodeIsland = "Rhode Island",
  SouthCarolina = "South Carolina",
  SouthDakota = "South Dakota",
  Tennessee = "Tennessee",
  Texas = "Texas",
  Utah = "Utah",
  Vermont = "Vermont",
  Virginia = "Virginia",
  Washington = "Washington",
  WestVirginia = "West Virginia",
  Wisconsin = "Wisconsin",
  Wyoming = "Wyoming",
}

/**
 * @returns {State[]} An array of states that have Senate races
 */
export const getSenateRaceStates = () => {
  return [
    State.National,
    State.California,
    State.Connecticut,
    State.Delaware,
    State.Florida,
    State.Hawaii,
    State.Indiana,
    State.Maine,
    State.Maryland,
    State.Massachusetts,
    State.Michigan,
    State.Minnesota,
    State.Mississippi,
    State.Missouri,
    State.Montana,
    State.Nebraska,
    State.Nevada,
    State.NewJersey,
    State.NewMexico,
    State.NewYork,
    State.NorthDakota,
    State.Ohio,
    State.Pennsylvania,
    State.RhodeIsland,
    State.Tennessee,
    State.Texas,
    State.Utah,
    State.Vermont,
    State.Virginia,
    State.Washington,
    State.WestVirginia,
    State.Wisconsin,
    State.Wyoming,
  ];
};

/**
 * @returns {State[]} An array of states that have gubernatorial races
 */
export const getGubernatorialRaceStates = () => {
  return [
    State.Delaware,
    State.Indiana,
    State.Missouri,
    State.Montana,
    State.NewHampshire,
    State.NorthCarolina,
    State.NorthDakota,
    State.Utah,
    State.Vermont,
    State.Washington,
    State.WestVirginia,
  ];
};
